# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b0e009fa2abf4395c0705a65bf8e2da6198145b0d82e30b75d99c7052d5c9ce129098d1d32ca172a16250f783d3a150a0b4acf8abb06e8f71d0222032460919

test:
  secret_key_base: ba80d6ff139300a7a5edf0cdf36fc94412b46c042c2ae8e44f2ed7e4fa9f6072e9c25fd1131e9a6f4596272b26aa69fb9cd89ff7900a7781383d3f8cad559f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
